/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f0xx.h"

static volatile uint32_t Tick;

#define LED_TIME_BLINK 300
#define BUTTON_DEBOUNCE 40	//doba pro odstreanění zákmitu
#define LED_TIME_SHORT 100
#define LED_TIME_LONG 1000
#define BUTTON_DEBOUNCE_SHORT 5		//5ms vzorkování

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void EXTI0_1_IRQHandler(void)
 {
	if (EXTI->PR & EXTI_PR_PR0) { // check line 0 has triggered the IT
	 	 EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
	 	 GPIOB->ODR ^= (1<<4);
	}
 }

void SysTick_Handler(void)
{
	Tick++;
}


void blikac(void)
 {
	static uint32_t delay;
	if (Tick > delay + LED_TIME_BLINK) {
		GPIOA->ODR ^= (1<<4) ;
		delay = Tick;
	}
 }

void tlacitka (void)
{
	static uint32_t debounce1;
	static uint32_t debounce2; // vrozkování po 5ms
	static uint32_t off_time;


	if (Tick > debounce1 + BUTTON_DEBOUNCE) { //Tick větší jak 40ms proběhne vzorkování

		static uint32_t old_s2;				//nese starý stav talčítka S2
		uint32_t new_s2 = GPIOC->IDR & (1<<0);	//automatická proměná ,která nese aktuální hodnotu tlačítka S2

		if (old_s2 && !new_s2) { // testujeme sestupnou hranu, starý stav=1 a zárověň nový stav =0
			off_time = Tick + LED_TIME_SHORT;
			GPIOB->BSRR = (1<<0);
		}
		old_s2 = new_s2;

		if (Tick > debounce2 + BUTTON_DEBOUNCE_SHORT) {
			static uint16_t debounce = 0xFFFF;		//a proč je v návodě 0x7FFF???

			debounce <<=1;
			if (GPIOC->IDR & (1<<1)) debounce |= 0x0001;		//zlož na nejniší bit 1, zůstane vše kromě nejnižšího
			if (debounce == 8000){
				GPIOB->BSRR = (1<<0);
			}
		}
	}

	if (Tick > off_time) {	//po uplynutí doby led=0
		GPIOB->BRR = (1<<0);
	}
}

int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup

	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	SysTick_Config(8000); // 1ms

    /* Loop forever */
	for(;;) {
		blikac();
		tlacitka();

	}
}
